# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
        ('mycourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('FK_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_course', to='mycourses.Courses')),
                ('FK_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_student', to='loginapp.Users')),
            ],
        ),
    ]
