# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0002_auto_20160918_0209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursedescriptions',
            table='coursedescription',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
