# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0003_auto_20160918_0245'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursedescriptions',
            table='coursedescriptions',
        ),
    ]
