# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0004_auto_20160918_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedescriptions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
    ]
