# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0005_auto_20160920_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedescriptions',
            name='FK_course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='mycourses.Courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='coursedescriptions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
    ]
