# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0006_auto_20160920_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='cost',
        ),
    ]
